### ISSUE TITLE
Front-end tests

### ISSUE THREAD

**Issue by silvuss** [CoyoteNET/CoyoteNET-backend#10]
This issue is about to be a discussion on how to create **front-end** tests in this project, and what tools/services will be most appropriate for it.

The first mention about testing front-end comes from this post on 4programmers.net forum (by msm): https://4programmers.net/Forum/1578596. msm mentioned about the [**Selenium**](https://en.wikipedia.org/wiki/Selenium_(software)) tool. The general idea he is about is that:
1. The tests might be managed by a CI service used within this project.
2. They might be written in the way that will allow applying them also to the 4programmers.net forum front-end (he relates this to our purpose of creating a very similar project to 4programmers.net forum).

**Comment by dotNETSanta** [comment]
It was already used, but for some reason with was removed during separation.

https://github.com/dotNETSanta/Coyote.NETCore/blob/9fbf70453bde3c2793b57a1278dbb97c8cee27c0/Coyote/CoyoteNETCore.Tests/FrontEnd.cs

**Comment by silvuss** [comment]
@dotNETSanta I do not understand – may you explain why you closed this issue? Although I can see there are Selenium already somehow incorporated, I think it will still be OK to discuss whether it is a good option.

**Comment by Kubion70** [comment]
Create this issue in frontend repository. But still, I think it's to early to think about tests.
