### ISSUE TITLE
Set default branch to "development"

### ISSUE THREAD

**Issue by silvuss** [CoyoteNET/CoyoteNET-backend#12]
### Problem

Currently, the default branch is "master". Would it be OK to set the "development" branch as default? I'm referring to that it may cause some troubles when committing **directly from GitHub**.

For example, when I want to edit README directly from GitHub, I must remember to firstly change the branch to "development" – or else the only way I could make a commit with my changes is to create a new branch.

I'm not sure whether and how changing default branch will bias any other commits/actions in GitHub (either remote or direct).

### Current behavior

The default branch is "master".

### Expected behavior

The default branch is "development".

**Comment by smknd** [comment]
I would rather remove `development` branch at all. What is the value of that?
We can follow much simpler approach with branch per feature and directly merge to `master`.

**Comment by silvuss** [comment]
@smknd In general, a development branch is part of a specific Git workflow (so, also "GitHub's workflow"), where . [This Atlasian blog post](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) mentions such an aproach. Also, [this Beanstalk guide](http://guides.beanstalkapp.com/version-control/branching-best-practices.html) is a good introduction to such type of workflow.

**Comment by smknd** [comment]
OK, but what is better in keeping changes for some time in the `development` branch instead of merging directly to `master` and immediately deploy to production?

**Comment by silvuss** [comment]
@smknd 

A quote from http://guides.beanstalkapp.com/version-control/branching-best-practices.html:
> Another reason to use version control is so that you can use your repository as the source to deploy code to your servers. Much like feature and bug-fix branches, environment branches [e.g. "development" branch] make it easy for you to separate your in-progress code from your stable code. **Using environment branches and deploying from them means you will always know exactly what code is running on your servers in each of your environments.**

Two quotes from https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow:
> This workflow [Gitflow] doesn’t add any new concepts or commands beyond what’s required for the Feature Branch Workflow. **Instead, it assigns very specific roles to different branches and defines how and when they should interact.**

> **The master branch stores the official release history, and the develop branch serves as an integration branch for features.**

All of the above better organize the workflow for me than a single master branch. Firstly, this workflow let me know where the stable code of the latest release is (in the "master" branch), so I know what code I should apply the bugfixes to. Secondly, it let me know what code I should use for new features (the "development" branch).

There are certainly another useful workflows in Git, so willingly I would get to know all other's opinions.

**Comment by dotNETSanta** [comment]
What about storing our stable versions in "Releases"?

https://github.com/CoyoteNET/CoyoteNET-backend/releases

**Comment by dotNETSanta** [comment]
So, anybody has anything against this approach?

PR -> review -> master -> stable version -> release

**Comment by smknd** [comment]
By `stable version` you mean tag on `master`?

**Comment by silvuss** [comment]
@dotNETSanta I don't understand this approach. I was thinking rather about:
1. `git checkout -b newBranch`
2. PR -> review / direct commit
3. when `newBranch` is done -> `git checkout development && git merge newBranch`
4.1. if all tests passed -> `git remove newBranch && git checkout master && git merge development`
4.2. if any test failed -> `git checkout newBranch`, fix, then go to 3.

**Comment by dotNETSanta** [comment]
@smknd 

No, I meant actually stable version that has been used and of course tested (automat)

@silvuss 

So, kind of the same approach? but without Development branch

FeatureBranch -> 

Feature seems to be completed ->

 PR / Review with Tests now. Not later. -> 

    if tests passed -> merge + remove that FeatureBranch

    if failed -> (stays in review / is rejected) and PR has to repeat whole process

after having X features we're relasing current version as "Release"

**Comment by silvuss** [comment]
@dotNETSanta Does your proposition assumes that tests will be run on every feature branch? Does it assumes that every feature branch will be a PR?

**Comment by dotNETSanta** [comment]
@silvuss 

``Does your proposition assume that tests will be run on every feature branch? ``

No, it assumes that everything that wants to be in Master has to go through PR where it'll be tested by Appveyor and Reviewed by used.

`` Does it assume that every feature branch is a PR?``

Well, no.

**Comment by silvuss** [comment]
> everything that wants to be in Master has to go through PR

But it does mean every feature branch will be a PR?

**Comment by smknd** [comment]
I think it's quite obvious that every feature or bugfix branch must have PR.

**Comment by silvuss** [comment]
Closing. The issue is no longer relevant since the development branch has been removed.
