### ISSUE TITLE
The entity "Users" in the logical data model lacks of an attribute related to the e-mail of a user

### ISSUE THREAD

**Issue by silvuss** [CoyoteNET/CoyoteNET-backend#33]
Currently, in the logical data model, there is not attribute related to the e-mail of a user in the entity "Users". But, since it is already described in the back-end functional requirements that a user receives e-mails from the system, that is an inconsistency. Such an attribute should be added.

**Comment by dotNETSanta** [comment]
Done.

**Comment by silvuss** [comment]
The attribute has been added.
