### ISSUE TITLE
The attribute "Title" is wrongly added to the entity "Posts" instead of the entity "Threads" in the logical data model

### ISSUE THREAD

**Issue by silvuss** [CoyoteNET/CoyoteNET-backend#34]
Currently, in the logical data model, the entity "Posts" has the attribute for title ("Title"), and the entity "Threads" has no such attribute. But, since a post could not logically have a title, but a thread should, that is an inconsistency. The attribute "Title" should be removed from the entity "Posts" and added to the entity "Threads".

**Comment by dotNETSanta** [comment]
Done.

**Comment by silvuss** [comment]
The attribute has been moved.
