### ISSUE TITLE
The entity "E-mail messages sending log" in the logical data model lacks of an attribute related to the type of an e-mail

### ISSUE THREAD

**Issue by silvuss** [CoyoteNET/CoyoteNET-backend#35]
Currently, in the logical data model, the entity "E-mail messages sending log" has no attribute related to the type of an e-mail. Since there is already an entity "E-mail messages types" in the model, that is an inconsistency. Such an attribute should be added to that entity.

**Comment by dotNETSanta** [comment]
Done.

**Comment by silvuss** [comment]
An attribute has been added.
