### ISSUE TITLE
Benefits of implementing 4 tables for notifications instead of 1

### ISSUE THREAD

**Issue by silvuss** [CoyoteNET/CoyoteNET-backend#36]
Currently, in the logical data model, there are proposed 4 entities that are to store notifications:
- "Post notifications",
- "Thread notifications",
- "Thread category notifications",
- "Microblog entry notifications".

@dotNETSanta and I recently started such a discussion in the issue #31 whether it will be more efficient to have 4 tables instead of one (i.e. having the aforementioned entities implemented).

I have argued that, when it comes to gather notifications (as a result of creating comments etc.), it shall be more efficient to have the possibility of asynchronously saving them into mulltiple tables. 

@dotNETSanta argued that, when it comes to sending notifications, it shall be more efficient not to have the requirement of searching multiple tables.

I suspect that we both are talking about different ways of handling sending notifications to users. The purpose of this issue is to discuss it. @smknd , may you comment on it?

**Comment by dotNETSanta** [comment]
I just did very simple comparison:

1 table with 100k records where 3336 of them belong to our user 

4 tables with 25k total records per table where 834 of them belong to our user 


	Console.Clear();
	var dt1 = DateTime.Now;

	var notifications = await _ct
	.Users
	.Include(x => x.NotificationsA)
	.Include(x => x.NotificationsB)
	.Include(x => x.NotificationsC)
	.Include(x => x.NotificationsD)
	.FirstOrDefaultAsync(x => x.Id == "7d212e28-c234-40da-918f-20876a98cadd");

	var dt2 = DateTime.Now;
	Console.WriteLine((dt2 - dt1).TotalMilliseconds + "ms");


	Console.Clear();
	var dt1 = DateTime.Now;

	var notifications = await _ct
	.Users
	.Include(x => x.NotificationsA)
	.Include(x => x.NotificationsB)
	.Include(x => x.NotificationsC)
	.Include(x => x.NotificationsD)
	.FirstOrDefaultAsync(x => x.Id == "7d212e28-c234-40da-918f-20876a98cadd");

	var dt2 = DateTime.Now;
	Console.WriteLine((dt2 - dt1).TotalMilliseconds + "ms");


After executing those queries 13 times the sum of ms was 23118 for 4 tables and 24428 for 1 table, so around 5% difference

Here are queries:

	SELECT TOP(1) [x].[Id], [x].[Name]
	FROM [Users] AS [x]
	WHERE [x].[Id] = N'7d212e28-c234-40da-918f-20876a98cadd'
	ORDER BY [x].[Id]

	SELECT [x.NotificationsA].[Id], [x.NotificationsA].[AlreadyRead], [x.NotificationsA].[BroadcastedAt], [x.NotificationsA].[Description], [x.NotificationsA].[Name], [x.NotificationsA].[UserId]
	FROM [TestsA] AS [x.NotificationsA]
	INNER JOIN (
		SELECT TOP(1) [x0].[Id]
		FROM [Users] AS [x0]
		WHERE [x0].[Id] = N'7d212e28-c234-40da-918f-20876a98cadd'
		ORDER BY [x0].[Id]
	) AS [t] ON [x.NotificationsA].[UserId] = [t].[Id]
	ORDER BY [t].[Id]

	SELECT [x.NotificationsB].[Id], [x.NotificationsB].[AlreadyRead], [x.NotificationsB].[BroadcastedAt], [x.NotificationsB].[Description], [x.NotificationsB].[Name], [x.NotificationsB].[UserId]
	FROM [TestsB] AS [x.NotificationsB]
	INNER JOIN (
		SELECT TOP(1) [x1].[Id]
		FROM [Users] AS [x1]
		WHERE [x1].[Id] = N'7d212e28-c234-40da-918f-20876a98cadd'
		ORDER BY [x1].[Id]
	) AS [t0] ON [x.NotificationsB].[UserId] = [t0].[Id]
	ORDER BY [t0].[Id]

	SELECT [x.NotificationsC].[Id], [x.NotificationsC].[AlreadyRead], [x.NotificationsC].[BroadcastedAt], [x.NotificationsC].[Description], [x.NotificationsC].[Name], [x.NotificationsC].[UserId]
	FROM [TestsC] AS [x.NotificationsC]
	INNER JOIN (
		SELECT TOP(1) [x2].[Id]
		FROM [Users] AS [x2]
		WHERE [x2].[Id] = N'7d212e28-c234-40da-918f-20876a98cadd'
		ORDER BY [x2].[Id]
	) AS [t1] ON [x.NotificationsC].[UserId] = [t1].[Id]
	ORDER BY [t1].[Id]

	SELECT [x.NotificationsD].[Id], [x.NotificationsD].[AlreadyRead], [x.NotificationsD].[BroadcastedAt], [x.NotificationsD].[Description], [x.NotificationsD].[Name], [x.NotificationsD].[UserId]
	FROM [TestsD] AS [x.NotificationsD]
	INNER JOIN (
		SELECT TOP(1) [x3].[Id]
		FROM [Users] AS [x3]
		WHERE [x3].[Id] = N'7d212e28-c234-40da-918f-20876a98cadd'
		ORDER BY [x3].[Id]
	) AS [t2] ON [x.NotificationsD].[UserId] = [t2].[Id]
	ORDER BY [t2].[Id]

Versus

	SELECT TOP(1) [x].[Id], [x].[Name]
	FROM [Users] AS [x]
	WHERE [x].[Id] = N'7d212e28-c234-40da-918f-20876a98cadd'
	ORDER BY [x].[Id]

	SELECT [x.Notifications].[Id], [x.Notifications].[AlreadyRead], [x.Notifications].[BroadcastedAt], [x.Notifications].[Description], [x.Notifications].[Name], [x.Notifications].[UserId]
	FROM [Tests] AS [x.Notifications]
	INNER JOIN (
		SELECT TOP(1) [x0].[Id]
		FROM [Users] AS [x0]
		WHERE [x0].[Id] = N'7d212e28-c234-40da-918f-20876a98cadd'
		ORDER BY [x0].[Id]
	) AS [t] ON [x.Notifications].[UserId] = [t].[Id]
	ORDER BY [t].[Id]
	
1 Tab
<img src="https://i.imgur.com/yJ3JQLf.png" />

4 Tabs
<img src="https://i.imgur.com/W0PAzEL.png" />

But I'm not sure whether this methodology is flawed or not and I didnt do anything on database manually (indexes and so on), just relied on db created by EF Core.

**Comment by smknd** [comment]
I don't understand what `sending notifications` mean in the context of the database. Notifications should be retrieved from the database and displayed to the logged-in user, that's all.

I'm also not aware if saving rows to many tables is faster than saving to one table if all these are part of one Database. In any case it has to be handled by the same RDBS on the same machine.

Beside the performance, the thing which matters most is how easy is to maintain and extend the code. In the future, when we have to add new type of notification, would be much better if we add new enum and put rows in the same table instead of creating a new table every time. 
So I vote to have only one table.

**Comment by silvuss** [comment]
@smknd "Sending notifications" means exactly what you have written.

Since a while ago I have thought it over, it seems that you are right that there shall not be any differentiation of the "sending flow".

I am not closing this issue yet, because I wonder if I the following flow is appropriate for our project. May you check it?

1) a post is created; then, 2) a function creates all necessary notifications in appropriate tables, and then 3) it calls another function, giving it the notification list, and that function sends all notifications from that list.

**Comment by dotNETSanta** [comment]
* A) a post is created; then,

* B) a function creates all necessary notifications in appropriate TABLE, and then 

I think C should be some Queue-ish thing that'll manage that - some external app? background service?

**Comment by dotNETSanta** [comment]
* A) a post is created; then,

* B) a function creates all necessary notifications in appropriate table/tables, and then 

I think C should be some Queue-ish thing that'll manage that - some external app? background service?

**Comment by smknd** [comment]
Let's try to be a bit more precise:

1. User sends SavePostRequest, it's handled by SavePostRequestHandler;
2. SavePostRequestHandler stores data in DB and raises an PostSavedEvent;
3. All event handlers which can handle that event does their job - mostly by storing in DB. 
a. If user is logged in, some event handler will send notification to browser, to update de UI.
b. If user is not logged in, he will see notifications after entering the site.

**Comment by silvuss** [comment]
@smknd That looks pretty good and understandable to me. Thank you. @dotNETSanta, do you agree? May we close?

**Comment by dotNETSanta** [comment]
tl:dr to the main post

1 table that's using "notification type"

**Comment by silvuss** [comment]
I was asking whether you were agreeing with @smknd last statement ;), but anyway.
